[global_tags]
  agent = "telegraf"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  container_names = []
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  perdevice = true
  total = false
  docker_label_include = []
  docker_label_exclude = []

[[inputs.ping]]
urls = ["sidn.nl", "sanmartin.dev", "1.1.1.1", "google.com", "reddit.com", "twitter.com", "amazon.in"]
count = 4
ping_interval = 1.0
timeout = 2.0

[[inputs.dns_query]]
  servers = ["9.9.9.9"]
  domains = ["sanmartin.io", "google.com", "reddit.com", "twitter.com", "amazon.in", "zerodha.com"]

[[outputs.prometheus_client]]
  listen = ":9283"
  metric_version = 2

[[outputs.http]]
  # Victoriametrics instance
  url = "http://labs.sanmartin.io:8428/api/v1/write"
  data_format = "prometheusremotewrite"
  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
