apiVersion: 1

datasources:
    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://victoriametrics:8428
      isDefault: true

    - name: VictoriaMetrics - cluster
      type: prometheus
      access: proxy
      url: http://vmselect:8481/select/0/prometheus
      isDefault: false

    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      basicAuth: false
      isDefault: false
      version: 1
      editable: false